# Generated by Django 4.2.4 on 2023-08-19 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cell_phone',
            field=models.DecimalField(decimal_places=0, max_digits=11, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='Сотовый телефон'),
        ),
        migrations.AlterField(
            model_name='person',
            name='work_phone',
            field=models.DecimalField(decimal_places=0, max_digits=11, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='Рабочий телефон'),
        ),
    ]
