# Generated by Django 4.2.4 on 2023-08-19 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_person_cell_phone_alter_person_work_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cell_phone',
            field=models.DecimalField(decimal_places=0, max_digits=11, validators=[django.core.validators.MinLengthValidator(limit_value=11)], verbose_name='Сотовый телефон'),
        ),
        migrations.AlterField(
            model_name='person',
            name='work_phone',
            field=models.DecimalField(decimal_places=0, max_digits=11, validators=[django.core.validators.MinLengthValidator(limit_value=11)], verbose_name='Рабочий телефон'),
        ),
    ]
